### ISSUE TITLE
No icons appear

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.kde.okular#1]
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Qt: Session management error: Could not open network socket
Icon theme "Azure-theme-master" not found.
Icon theme "Azure-theme-master" not found.
unknown tag graphic-properties
unknown tag graphic-properties
unknown tag graphic-properties
unknown tag table-properties
unknown tag table-row-properties
unknown tag outline-style
unknown tag notes-configuration
unknown tag notes-configuration
unknown tag linenumbering-configuration
unknown tag default-page-layout
Illegal icon group:  7
Illegal icon group:  7

![captura de tela de 2018-04-28 21-29-42](https://user-images.githubusercontent.com/26097419/39402032-4fd79f92-4b2b-11e8-8502-c6bab8a17679.png)

**Comment by nedrichards** [comment]
Can you make sure you have the following installed and test again:

> flatpak install flathub org.kde.PlatformTheme.QGnomePlatform//5.10 
> flatpak install flathub org.kde.KStyle.Adwaita//5.10 

I think there was an issue that the correct platform theme and style weren't being installed.

**Comment by Ethunxxx** [comment]
I encounter the same problem, and in my case the icons do not appear after installing the theme and style flatpaks, unfortunately.
