### ISSUE TITLE
Not abile to change "Annotation font" !

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.kde.okular#105]
Hi. I think that this bug is flatpak specific. 

I'm unable to change font of text of "Typewriter", "Inline Note" & "Popup Note". I tried both English & Arabic but not worked!

When I tried "Annotation Note", all fonts are listed correctly. But no change in font whatever I select.

Best.

**Comment by tsdgeos** [comment]
Not flatpak specific, that's a regular okular bug.
