### ISSUE TITLE
"Arrow", "Straight line", "Polygon" annotations not worked at all !

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.kde.okular#111]
Hi.
I have last version from flatpak package (20.12.1).
I noticed that "Arrow", "Straight line", & "Polygon" annotations not working, currently, at all !
Kindly, to see if this flatpak specific or not.
Best.

**Comment by tsdgeos** [comment]
>  I noticed that "Arrow", "Straight line", & "Polygon" annotations not working, currently, at all !

What do you mean Arrow doesn't work?

Could you record a video?

**Comment by Nokia808** [comment]
@tsdgeos 
Hi. This issue is wrong ! It seem that you changed the way by which these annotations are used ! Previously - if I'm not confused - I was need to left-click with dragging of mouse pointer while still left-clicking (which still the case for "rectangle" & "ellipse" ..... Now this is changed: I need to just left-click then release left-click & pove mouse pointer to other point then left-clicking again to bring any of those annotations.

I will closed this issue.
