### ISSUE TITLE
“http://github.com/flathub/org.kde.okular” is unable to be invoked by startplasma-wayland.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [flathub/org.kde.okular#122]
> ```
> PS /home/beedellrokejulianlockhart> flatpak install org.kde.okular
> Looking for matches…
> Remotes found with refs similar to ‘org.kde.okular’:
> 
>    1) ‘flathub’ (system)
>    2) ‘kdeapps’ (system)
> 
> Which do you want to use (0 to abort)? [0-2]: 1
> 
> org.kde.okular permissions:
>     ipc                  network      cups      pulseaudio      wayland      x11     dri     file access [1]
>     dbus access [2]
> 
>     [1] host, xdg-config/kdeglobals:ro
>     [2] com.canonical.AppMenu.Registrar
> 
> 
>         ID                             Branch          Op          Remote          Download
>  1. [✓] org.kde.okular.Locale          stable          i           flathub          8.0 kB / 3.1 MB
>  2. [✓] org.kde.okular                 stable          i           flathub         58.9 MB / 66.6 MB
> 
> Installation complete.
> PS /home/beedellrokejulianlockhart> flatpak run org.kde.okular    
> qt.qpa.xcb: could not connect to display 
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, > wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
> ```

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
This problem has been remediated.

**Comment by rezad1393** [comment]
can this be done automatically when wayland is detected?

**Comment by Erick555** [comment]
Currently this app intentionally disables native wayland support. Removing [--env=QT_QPA_PLATFORM=xcb](https://github.com/flathub/org.kde.okular/blame/master/org.kde.okular.json) from manifest would fix this.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@Erick555, if that overrision is unnecessary, as I believe it to be, please create a merge-request.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
I have realized that I may have erroneously closed this. Does this problem persist?

**Comment by travier** [comment]
Okular works for me on Wayland.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@travier, without necessitating [`flatpak run --unset-env=QT_QPA_PLATFORM org.kde.okular`](http://github.com/flathub/org.kde.okular/issues/122#issuecomment-892749790:~:text=try%20flatpak%20run%20--unset-env%3Dqt_qpa_platform%20org.kde.okular)?

**Comment by travier** [comment]
yes
