### ISSUE TITLE
How to set defaults for Print to PDF?

### ISSUE THREAD

**Issue by 8W3oybHJdYzBex** [flathub/org.kde.okular#138]
How can you set default options/properties for the virtual printer "Print to File (PDF)"? (For example, changing the output page size from A4 to letter)

If I'm not mistaken, "Print to File (PDF)" is a KDE feature rather than an Okular-specific feature, but I can't find any mention of configuring it in the [org.kde.Platform repo](https://invent.kde.org/packaging/flatpak-kde-runtime) either.

To be clear, I am not talking about CUPS-PDF, though CUPS-PDF would probably be a viable alternative.

**Comment by travier** [comment]
Is it possible to set default on regular (non-Flatpak) Okular?

**Comment by 8W3oybHJdYzBex** [comment]
> Is it possible to set default on regular (non-Flatpak) Okular?

Indeed, I should have checked this before opening the issue. It seems to be an open issue with the Qt printing infrastructure, which KDE adopted since KDE 4. I saw an [old screenshot](https://goinglinux.com/articles/PrintToPDF_en.htm) that suggested it was configurable, but there is no such configuration in KDE Plasma 5.

Relevant links:
https://forum.kde.org/viewtopic.php?t=170871
https://www.reddit.com/r/kde/comments/owlebm

Relevant links from old versions:
https://forum.kde.org/viewtopic.php?t=124376
https://bugs.kde.org/show_bug.cgi?id=176999
https://bugreports.qt.io/browse/QTBUG-6469
https://bugreports.qt.io/browse/QTBUG-69562

Through investigating this issue, I have come to the conclusion that [printing in Qt is a mess with many semi-major issues still unfixed years later](https://bugreports.qt.io/issues/?jql=project%20%3D%20QTBUG%20AND%20component%20%3D%20%22GUI%3A%20Printing%22) (e.g. printing in A4 even when Letter is selected). I will use CUPS-PDF going forward.

<br>

**Closed as unresolved, upstream issue.**
