### ISSUE TITLE
'Could not change permissions for file.pdf'

### ISSUE THREAD

**Issue by ysteina** [flathub/org.kde.okular#15]
Whenever I make annotations or other changes to a PDF file, Okular gives me the following message: "Could not change permissions for «/run/user/1000/doc/95e8f59/test.pdf»" (translated from Norwegian). The changes to the PDF are still saved, though, and viewable with non-Flatpak Okular. :-)

These are PDF files located in /home/ or /home/Documents/.

OS: Kubuntu 18.10 Beta
Flatpak and xdg-desktop-portal version 1.0.2
xdg-desktop-portal-kde 5.13.5

**Comment by jialinyi94** [comment]
Same here.
OS: ubuntu 18.04

**Comment by ysteina** [comment]
Still an issue with the latest Okular flatpak (1.6.0) on Kubuntu 18.10, now with Flatpak 1.0.4 (can't try 1.0.6 because the official ppa doesn't support 18.10).

**Comment by jaaquino** [comment]
I get this too (Okular v. 1.6.0, Linux Mint 18.3, Flatpak 1.0.3). Doesn't seem to be a problem, though. File seems to save okay. And though the file browser opens on the root [ / ] folder that doesn't seem to actually alter the file permissions in the first place. Not sure what it all means... just glad to be able to use this version of Okular, with its improved annotation tools.

**Comment by peey** [comment]
Affects me as well. Ubuntu 16.04. The prompt is annoying as I habitually press ctrl+s often

**Comment by felipehw** [comment]
The problem for me is resolved.
And this happens after I gave permission to Okular access my filesystems:
```
flatpak override --user --filesystem=/pathToDocuments/ --filesystem=/pathToOtherDocuments/ org.kde.okular
```
I don't know if this was solved by this command, by an update of okular flatpak or another hidden reason.

**Comment by eszlari** [comment]
Tested on Kubuntu 19.10, it works.
