### ISSUE TITLE
Digitally Sign crashes Okular

### ISSUE THREAD

**Issue by kranoner** [flathub/org.kde.okular#165]
I open a document to esign.
![image](https://user-images.githubusercontent.com/6149895/168232388-225b1687-2275-403c-bbd0-1c689dea494f.png)

I click on the menu "Tools", then "Digitally Sign..." 
![image](https://user-images.githubusercontent.com/6149895/168232597-b42a2ace-a321-43a2-935f-e7047a715e2a.png)

I draw a box to insert eSignature and select the certificate to use:
![image](https://user-images.githubusercontent.com/6149895/168232774-32794273-0ae8-469d-aea6-950df01b053e.png)

I enter a new filename to save the newly created and signed PDF document:
![image](https://user-images.githubusercontent.com/6149895/168233032-b7b90229-a8ea-4688-9a21-b36c570bc486.png)

I click on save, and it crashes. The console shows the error: 
`qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 11085, resource id: 15377668, major code: 40 (TranslateCoords), minor code: 0`

I dentified this issue with the following commits (Okular 22.04.1): 
6bc6bb51249821d611dbd60450b909cca609c6675b102d6060d29d164dd78645
37f8f2bc32af5750de55b6d101bf8e45cee967d03219067a490c8d75ea94dc6c
d1d5545d0642b0870db0d88e8d9d434daeec01cad27c3de33239b75cc74b956c
while the digital signature was working well with older commit and Okular 22.04.0

**Comment by travier** [comment]
Thanks for the report. Please file a bug upstream.

**Comment by tsdgeos** [comment]
Do you get a crash dialog?

**Comment by kranoner** [comment]
> The console shows the error:
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 11085, resource id: 15377668, major code: 40 (TranslateCoords), minor code: 0

**Comment by tsdgeos** [comment]
That's not a real error, more a warning than anything.
