### ISSUE TITLE
Failed to open PDF with "Could not open file://path/to/file.pdf"

### ISSUE THREAD

**Issue by KikiSyahadat** [flathub/org.kde.okular#2]
When I ran from terminal:

> Qt: Session management error: Could not open network socket
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Connection refused
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Connection refused
org.kde.knotifications: Audio notification requested, but sound file from notifyrc file was not found, aborting audio notification

I am using openSUSE Tumbleweed with KDE Plasma 5

**Comment by tsdgeos** [comment]
Do you still have this issue?

**Comment by KikiSyahadat** [comment]
Never tested it anymore, I went back to official Tumbleweed repositories, sorry. The response from the devs was too long.

**Comment by tsdgeos** [comment]
Closing since it works for me and the reporter doesn't seem interested in it anymore
