### ISSUE TITLE
Can't print or view any existing printers.

### ISSUE THREAD

**Issue by Richy91** [flathub/org.kde.okular#25]
I am using latest flatpak version from ppa:alexlarsson/flatpak and latest version of okular on ubuntu 18.04.
Issue is that I can't print document, because okular doesn't show my printer (the same with others). 
Works with evince flatpak!

Is there a flatpak run option which i can try or this is a bug?

**Comment by tsdgeos** [comment]
@grulja do you remember what's the status of printing? is it coming in Qt 5.12? 5.13? or was it missing?

**Comment by grulja** [comment]
Support for printing is still missing unfortunately.

**Comment by fedelibre** [comment]
@grulja Can you elaborate? I guess that a regular installation of Okular comes with printing features. It's just a flatpak problem?

**Comment by grulja** [comment]
It's basically a sandbox limitation. There is a portal API which we can use, but nobody has implemented it into Qt yet.

**Comment by tsdgeos** [comment]
@grulja so this should be fixed by your latest commit, right?

**Comment by grulja** [comment]
> @grulja so this should be fixed by your latest commit, right?

Yes, but only for those who run Flatpak 1.6 and newer.
