### ISSUE TITLE
Saving document with resized text creates huge memory footprint

### ISSUE THREAD

**Issue by krisutofu** [flathub/org.kde.okular#280]
This issue haunts me for a longer time and I'd like to share it with you.

When I browse my PDF and I add an annotation to the slides or form, sometimes the selected font size is too small or large. When I resize the text (same for annotated text inside a box) and save it, it will not only take a long time but the size of the PDF will get huge, more than 100MiB are added when saving! Going from 2 MiB to 103MiB! This is like saving a high-resolution image for every character in the alphabet. This memory waste is added to each affected document.

There are significant problems
- **It cannot be undone!!** Saving after removing the change that inflated the file will not help. The only way to regain the previous size is to scrap the document with all annotations and redownload the original one, creating new annotations.
- file becomes too large for emails, uploading or submission with size restrictions
- it wastes a lot of memory for no good reason
- it's the size of a large or long compressed video

If the issue cannot be fixed, there are some intermediate but weak solutions:
- export + import of annotations between documents (it should work at least for equal documents)
- if the problem occurs, warn users and let them cancel the saving process
- allow changes made by saving to be undone completely

Version: Flathub, installed via Software Center on Ubuntu 20.04.3 LTS.

**Comment by travier** [comment]
This looks like non-Flatpak specific issues that should be raised as a bug at https://bugs.kde.org/enter_bug.cgi?format=guided&product=okular

**Comment by krisutofu** [comment]
> This looks like non-Flatpak specific issues that should be raised as a bug at https://bugs.kde.org/enter_bug.cgi?format=guided&product=okular

Oh, I am sorry. Thanks.

**Comment by krisutofu** [comment]
[Bug report](https://bugs.kde.org/show_bug.cgi?id=470128)
