### ISSUE TITLE
Limitation with opening tabs in Windows

### ISSUE THREAD

**Issue by tikkatek** [flathub/org.kde.okular#353]
This is similar to another issue [Cannot open files in new tabs #36](https://github.com/flathub/org.kde.okular/issues/36), but specific to MS Windows.

I am using Windows 11 and installed the stable version of Okular from the [Microsoft App Store](https://www.microsoft.com/store/productId/9N41MSQ1WNM8) and enabled the following options:

- Open new files in tabs
- Switch to existing tab if file is already open

Screenshot of config
![image](https://github.com/flathub/org.kde.okular/assets/26571381/516e7676-4a01-4dd0-b6c2-6d477ba6f0fe)

Okular has been made the default PDF reader on my system. But if I try to open a document from file explorer (double-click the document icon), a new window/instance of Okular is created with that documented. Is this expected? If I opened another PDF from within the Okular interface (Ctrl+O), the a new tab is opened with the existing window/instance.

Am I doing something wrong?

**Comment by travier** [comment]
This is not the place to report issues on Windows.

**Comment by travier** [comment]
Please report this upstream to https://bugs.kde.org/

**Comment by tikkatek** [comment]
Oops. Sorry.
