### ISSUE TITLE
CHM files do not open

### ISSUE THREAD

**Issue by HananKrishna** [flathub/org.kde.okular#372]
According to the Flathub page for Okular, the program should be capable of running CHM files. But instead I see the following error message pop-up on my screen inside the Okular window.

```
Could not open file:///var/home/user/Downloads/file.chm. 
Can not find a plugin which is able to handle the document being passed.
```

This is on Okular 24.08.1
OS is Fedora Linux 40 Kinoite.

Is there any possible way I can try fixing this, or is CHM support dropped from Okular?

**Comment by Erick555** [comment]
According to buildlog CHM support should be enabled:

```
...
 * LibZip, A library for reading, creating, and modifying zip archives, <https://libzip.org/>
   Support CHM files in okular. You can make the dependency optional adding LibZip to the FORCE_NOT_REQUIRED_DEPENDENCIES cmake option
...
```
It's interesting that opening [CBR](https://github.com/flathub/org.kde.okular/issues/331) files also stopped working.

**Comment by HananKrishna** [comment]
I see there is discussion regarding CBR in issue #331. There is also a pull request #368 that unsuccessfully tries to resolve this.

Is this a problem related to libzip or is it still an issue with the Okular flatpak?

**Comment by tsdgeos** [comment]
Okular does not support CHM files anymore unfortunately

**Comment by tsdgeos** [comment]
Why do you need more confirmation than my confirmation?

**Comment by HananKrishna** [comment]
For reference if anyone else comes around searching for it. 
Having multiple spaces on the internet pointing to the code-source that states this change is a good idea as a form of redundant clarity.
