### ISSUE TITLE
copy and paste not working

### ISSUE THREAD

**Issue by username72764274** [flathub/org.kde.okular#41]
Running Fedora Silverblue 30 and the Okular flatpak version 9.08.1 stable from flathub it is not possible to copy text into the clipboard using Okular so that it could be used by other applications.
However, text added to the clipboard from other applications can be used within the Okular flatpak.

**Comment by eszlari** [comment]
Are you running a wayland session?

Does it work if start okular with

```
$ flatpak run --env=QT_QPA_PLATFORM=xcb org.kde.okular
```
?

**Comment by username72764274** [comment]
> Are you running a wayland session?
> 


Yes it runs in a wayland session.
> Does it work if start okular with
> 
> ```
> $ flatpak run --env=QT_QPA_PLATFORM=xcb org.kde.okular
> ```
> 
> ?

Yes. If I start the flatpak with the command mentioned above, copy and paste is working. Thanks for the hint. Is it possible to include this somehow in the flatpak itself, so that it is not necessary to start the flatpak with the stated command?

**Comment by Erick555** [comment]
@eszlari this forces running app on x which defeats the point of using wayland desktop session. I think it's not ok for default behavior. This should be reported upstream if they don't know about it already.

@username72764274 you can set `flatpak override --env=QT_QPA_PLATFORM=xcb org.kde.okular` once and it will always work for you but not interfere with everyone else usage of this app.

**Comment by eszlari** [comment]
@username72764274 Could you report the bug to https://bugs.kde.org ?

**Comment by eszlari** [comment]
@Erick555 Upstream KDE developers use this workaround themselves:
https://github.com/flathub/org.kde.kontact/commit/6d8b56937ef119cf68405f5fcc14323f19ca2be1

**Comment by Erick555** [comment]
@eszlari this commit is from year ago and mentions some graphics issue, not copy-paste problem. Also it mentions "probably until some of the upstream devs starts using Wayland" so it seems not coming from actual upstream developer.

**Comment by eszlari** [comment]
> so it seems not coming from actual upstream developer.

He is one:
https://www.dvratil.cz
https://github.com/KDE/akonadi/commits?author=danvratil
https://github.com/KDE/kmail/commits?author=danvratil

> If I install this app from distro repo and use wayland desktop session then it will run on wayland.

This is not true for SUSE Tumbleweed:
http://opensuse.14.x6.nabble.com/tumbleweed-kde-plasma-wayland-Primary-Selection-Protocol-middle-mouse-to-paste-td5104086.html
