### ISSUE TITLE
"Save to file" do not save !

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.kde.okular#58]
Hi. I'm on Fedora Linux 30 X64 bit Cinnamon version, using Okular as flatpak.
Currently I'm on version 1.9.2

I tried to used "Save to file" option as following:

Using Okular to open a PDF file | use "Area selection" | select an area within a page of PDF | click on "Save to file" | I select to save to my "Desktop" directory | click on "Save"
 
but I received the following message: "image saved to OCTET-STREAM file."

In fact no thing saved ! I tried other directories other than my "Desktop", but same error occurred & no thing saved !

Please your kind fix.

**Comment by grulja** [comment]
It works for me. Tested with both xdg-desktop-portal-gtk and xdg-desktop-portal-kde. I opened a pdf file and selected an area which I then saved as an image and the image was there.

Might be an issue in an older xdg-desktop-portal-[gtk] version? Can you run:
`rpm -q xdg-desktop-portal`
`rpm -q xdg-desktop-portal-gtk`

**Comment by Nokia808** [comment]
@grulja 
Take the output of commands that you asked me for:

```
$ rpm -q xdg-desktop-portal
xdg-desktop-portal-1.4.2-1.fc30.x86_64
```

```
$ rpm -q xdg-desktop-portal-gtk
xdg-desktop-portal-gtk-1.4.0-1.fc30.x86_64
```

**Comment by grulja** [comment]
Can you run `dbus-monitor --session`, keep it running and try to save the area selection and include the output from dbus-monitor here?

**Comment by Nokia808** [comment]
@grulja 
Hi. I did what you asked for. But the output is very huge, so I copy/past it to txt file & attached it here bellow.

I performed it as following:
- navigate to directory where PDF file located,
- open PDF by Okular
- then open terminal & run "dbus-monitor --session" command
- then tried to save the area selection
- finally closed okular
[dbus.txt](https://github.com/flathub/org.kde.okular/files/4267614/dbus.txt)

**Comment by Erick555** [comment]
> navigate to directory where PDF file located,

Is this dir located outside your `$HOME`?

**Comment by Nokia808** [comment]
@Erick555 
Hi. The PDF file located in a directory within my home.

**Comment by grulja** [comment]
From the log it is saved to `file:///home/user1945/Desktop/ffffff`. It is missing suffix, because in the GTK file chooser dialog, you have to type the suffix yourself. Maybe that's why you don't see that file again when opening it in Okular, because you are limited to *.pdf files?

**Comment by Nokia808** [comment]
@grulja 
Hi. I retried but when I used "saved as" dialog, I entered name of output file followed by .pdf then saved. It worked & saved as .pdf ! Moreover, I retried but using .jpeg & also worked & saved as .jpeg !
Only 2 issues:
1) you should add (or original developers in fact should add) note to "save as" dialog saying "You should enter extension with name for output file"
2) in both times (when I used .pdf & when I used .jpeg extension) after saving there was a message said "image saved to PNG file" though in fact I used .pdf & .jpeg extension at separate occasions ! What is this ?

**Comment by Erick555** [comment]
> you should add (or original developers in fact should add) note to "save as" dialog saying "You should enter extension with name for output file"

AFAIK this doesn't happen with kde dialog so it's gtk issue.

**Comment by grulja** [comment]
It's a gtk issue, I was already talking with gtk devs about this, it's behavior of their dialog which they don't consider as a bug so we cannot help here. Closing this as it's not an issue in Okular.
