### ISSUE TITLE
Add unrar for CBR support

### ISSUE THREAD

**Issue by barthalion** [flathub/org.kde.okular#61]
As described here: https://discourse.flathub.org/t/okular-flatpak-missing-unrar-to-read-comics-books-for-example/183/2

**Comment by albert-astals-cid-kdab** [comment]
The problem is that unrar is non free, and personally i'm not sure it's a great idea to ship non free software by default on the Okular flatpak in flathub.

@aleixpol has mentioned the existance of extensions, that are kind of plugins for flatpaks. That would solve the issue in a way that if someone wants to have CBR support by installing non-floss can do so but not everyone is forced to.

I'll have a look at how hard is to add such an extension

**Comment by barthalion** [comment]
While it's not free, it's free as in beer and the license allows redistribution. IMO that makes it good enough to bundle it. What do you think @flathub/admins?

**Comment by ramcq** [comment]
@tsdgeos Of course; it's the app publisher's decision what is published. @barthalion was just checking that Flathub would be OK either way - we would. Personally I think it's important that FOSS apps are installable/usable without non-FOSS dependencies, and I would like us to be able at some point to enable a repo URL / index that shows only FOSS apps and extensions - we of course want Okular to be present there and usable in a 100% free way.

So in this case, I would recommend investigating an extension as was discussed on the ticket already - obviously given the feature exists upstream, it's already been imagined by Okular developers that some people may make that choice to use `unrar` to access these files.

You can also select the default behaviour - whether the extension is automatically downloaded or not. `flatpak` has a new command `flatpak mask` which allows a user to say, even if this extension is flagged as auto-download, never fetch it, which would allow someone to avoid the default choice. Alternatively, you could say no autodownload, and there is a new feature in the "update portal" which allows an app to talk to Flatpak and request an extension is installed. In this case Okular could detect that you were running inside a Flatpak and trying to access a rar file, and ask Flatpak to install the extension.

**Comment by tsdgeos** [comment]
@ramcq is there any other documentation for extensions than https://github.com/flatpak/flatpak/wiki/Extensions ?

I am trying to understand what it says there but it seems a bit too short for me to totally grasp it, it also mentions something like 

```
[Extension org.gnome.Platform.GL]
version=1.4
directory=lib/GL
```

But where would that go? not the org.kde.okular.json file since that syntax doesn't seem compatible. But that's the only "flatpak" file we have in okular so i'm a bit lost :/

**Comment by Erick555** [comment]
@tsdgeos okular is able to open cbr files through [unarchiver](https://unarchiver.c3.cx/) which is LGPL. Perhaps this is better alternative than adding extension for unrar?

**Comment by Erick555** [comment]
You can take a look at fedora and/or arch build recipes:

https://src.fedoraproject.org/rpms/unar/blob/master/f/unar.spec

https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/unarchiver

**Comment by tsdgeos** [comment]
agreed, that's much better that unrar.

**Comment by tsdgeos** [comment]
but it needs the gcc ObjectiveC compiler that is not part of the Sdk :/

**Comment by tsdgeos** [comment]
Asked the SDK people at https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/979

**Comment by alexlarsson** [comment]
For extensions, I recommend looking at HexChat which has app plugin support:
https://github.com/flathub/io.github.Hexchat/blob/master/io.github.Hexchat.json
And a matching plugin:
https://github.com/flathub/io.github.Hexchat.Plugin.Perl/blob/master/io.github.Hexchat.Plugin.Perl.json

**Comment by alexlarsson** [comment]
I unfortunately don't think there is a great document or tutorial thing for extensions. But basically think of them like this "I, the $app, hereby declare that all installed ids matching $id or $id_prefix shall be made available (ie. the files are mounted there) in $dir when my app runs".

**Comment by tsdgeos** [comment]
Unfortunately the gcc objc support won't make it until 20.08 so need to wait until that it released so i can try compiling unarchiver.

**Comment by tsdgeos** [comment]
Solved in https://github.com/flathub/org.kde.okular/pull/95
