### ISSUE TITLE
Embedded files in document can't be opened due to sanboxed /tmp

### ISSUE THREAD

**Issue by Erick555** [flathub/org.kde.okular#62]
When document contains embedded files, they can't be opened. I can reproduce same behavior on non-flatpak okular when I force it to use xdg-portal (through `SNAP=1` env variable).

 To reproduce: 

1. Open document that contain embedded files
2. Go to `File -> Embedded Files`
3. Select embedded file and click `View`

**What happens:** nothing
**What should happen:** embedded file is opened, i.e. as new document if it's pdf

If in step `3` you chose to `Save` embedded file instead of `View` it works.

**Comment by tsdgeos** [comment]
Sadly it's something that can not be fixed from Okular itself, needs fixing from one of the libraries okular uses https://bugs.kde.org/show_bug.cgi?id=418835

**Comment by aleixpol** [comment]
So that I understand:
- it should be okular opening this file or something else in the system?
- where is the file that the other process (be it okular or otherwise) located? is it like `file:///mypdf?part=23`?

**Comment by Erick555** [comment]
If the embedded file is pdf (I didn't have other example) and xdg-portal isn't used:
- If _open files in tabs_ is checked it opens embedded document in new tab and there is only one okular process.
- If _open files in tabs_ is unchecked it opens embedded document in child okular process with runtime args `/usr/bin/okular /tmp/<embeded-filename>`

**Comment by Erick555** [comment]
So it seems the `/tmp` path is problem here. If I set `TMPDIR=/run/user/<uid>/app/org.kde.okular` viewing embedded file opens another portal where I can chose in which app it should be opened. The downside is it always opens it with new instance even when _open files in tabs is checked_ but that's not that much issue.

**Comment by tsdgeos** [comment]
> it should be okular opening this file or something else in the system?

It should be wathever app you have set to open that file type.

**Comment by tsdgeos** [comment]
> where is the file 
In /tmp (the /tmp of Okular flatpak)

**Comment by Erick555** [comment]
@tsdgeos the only way I see to fix this is to create wrapper script which will include:
```
#!/bin/sh
export TMPDIR="$XDG_RUNTIME_DIR/app/org.kde.okular"
exec /app/bin/okular "@"
```

**Comment by Erick555** [comment]
The easier but less secure alternative is to add `--filesystem=/tmp` to manifest.

**Comment by grulja** [comment]
I would make a wrapper like this:
`exec env TMPDIR=$XDG_CACHE_HOME /app/bin/okular \"$@\"
`
This is what we were using in Telegram. It should make Okular to put embedded files into **$HOME/.var/app/org.kde.okular/cache** where it should have correct permissions to open them in whatever application user wants to.

**Comment by Erick555** [comment]
Already proposed this in https://github.com/flathub/org.kde.okular/issues/62#issuecomment-599042557
