### ISSUE TITLE
"Page size" not working after adding it to toolbar

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.kde.okular#75]
Hi. I noticed that after I added "Page size" to toolbar (okular_part), it was added but not working because remain blank & did not show dimensions of current page !

I'm not sure wither this an Okular bug or a flatpak package specific issue, please check this from your side.

By the way, why Okular developers change site of this from lower boarder of program to be within toolbar ?? & is there a way to add it to lower boarder beside page number, where it was before & should located ?

**Comment by Nokia808** [comment]
Dear maintainer, regarding the site of "Page size" at lower boarder of UI of Okular, can you just check if this is really changed by Okular developers or it is other flatpak bug ? I have screenshot to old version - please see attachment named "measures" on this link:
https://bugs.kde.org/show_bug.cgi?id=380154

& here it is:
![measures](https://user-images.githubusercontent.com/25375330/80301921-72daaf80-8796-11ea-87b7-5827171e7afe.png)

I marked it by blue oval draw & red line point to it at lower right sector of image.

**Comment by tsdgeos** [comment]
The Page sizes action is not that blue thing, it's a thing that let's you select page sizes (if the document format supports it)

**Comment by Nokia808** [comment]
@tsdgeos 
Okay, now I understand. 
But where the "measures" that appeared in screenshot that I posted above for old version? It was show width & hight of page. Does this feature removed from Okular? Or it is a flatpak issue?

**Comment by tsdgeos** [comment]
They are in the same place

**Comment by Nokia808** [comment]
@tsdgeos 
Not appearing on my Okular ! See the following screenshot:

![no-measures](https://user-images.githubusercontent.com/25375330/80312392-886eca00-87d4-11ea-9f83-48f41761bc06.png)

**Comment by tsdgeos** [comment]
That's because all the pages have the same size, in that case you can check the page size in file->properties

**Comment by Nokia808** [comment]
@tsdgeos 
I understand now.

By the way, I see you on Okular repository on GitLab. Are you developer for Okular? Can you take care for this issue:
https://bugs.kde.org/show_bug.cgi?id=380154
See also:
https://gitlab.com/scarpetta/pdfmixtool/-/issues/43
Is there a home to address this issue ?

Also, I post other request, since long time, for add support to create/edit/delete outlines in Okular. Is there a hope to add this ?

I'm ready to donate Okular for supporting these 2 features (rulers + outlines support) .....

**Comment by tsdgeos** [comment]
Am i an okular developer? yes

I'm going to stop answering here, please use proper channels to discuss about those issues.

**Comment by Nokia808** [comment]
@tsdgeos 
Okay, I will discuss them on the Bugzilla. Kindly, replay me on them. They are the following:
https://bugs.kde.org/show_bug.cgi?id=377454
https://bugs.kde.org/show_bug.cgi?id=380154
https://bugs.kde.org/show_bug.cgi?id=379631

I'm now login in KDE bugzilla & I will discuss on the issue of "outlines" support:
https://bugs.kde.org/show_bug.cgi?id=377454

See you there ......
