### ISSUE TITLE
No "PDF printer" in printer list !

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.kde.okular#78]
Hi. I noticed that no "PDF printer" appearing in the list of available printers when I use "Print" option ! All the other printers installed on my device appearing but no "PDF printer" ! 

I'm not sure whether this is a bug in this flatpak package or it is new bug in Okular itself or it is related to the old version of flatpak on my system ?

I'm currently on flatpak version 1.4.4 & will upgrade my Fedora 30 at 1 / 6 / 2020, so currently & till time of upgrade my flatpak Okular is unable to print, though it show list of available printers ......

Kindly, investigate this issue.

**Comment by tsdgeos** [comment]
we need to build ps2pdf, good news is it's part of ghostscript which we're already building, just need to find the extra options to build and install it

**Comment by tsdgeos** [comment]
fixed in last update

**Comment by Nokia808** [comment]
@tsdgeos 
It is working 100% not just appear in printer list ! Good fix !
