### ISSUE TITLE
"Print Preview" do not working inspite Okular flatpak can printing okay !

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.kde.okular#82]
Hi.
Okular flatpak now can print okay. But there is still small issue, "Print Preview" still not working - see the following screenshot:

![print-preview](https://user-images.githubusercontent.com/25375330/83454411-acfd3800-a44b-11ea-926e-df9f2e8ab192.png)

**Comment by Erick555** [comment]
Is this a pdf? I tried multiple pdfs and preview works for all of them in ubuntu 20.04. They were in latin language so maybe this makes difference.

**Comment by Nokia808** [comment]
@Erick555 
1) Yes, it is a PDF,
2) It happened even with PDF with Latin contents - see bellow:

![latin](https://user-images.githubusercontent.com/25375330/83636123-f2794c80-a594-11ea-87df-02887cc860b2.png)

**Comment by Nokia808** [comment]
@Erick555 
By the way, I suffer from other issue: I tried to launch "Print Preview" with 990 page PDF file, & it failed even to show the above Window ! Moreover, when I tried to close it I received the following message: "Okular not responding, do you wait or force close it?"

What I have to do, open new issue or not? If yes, then where: here or on KDE BugZilla ?

**Comment by Nokia808** [comment]
@Erick555 
I do not know & can not know.

Regarding SELinux, I have no any error message from it. However, from my experiment SELinux can cause problem without any error message from it. Notable example is "dnscrypt-proxy-gui" which can not be launched since Fedora 28 till now due to SELinux problem WITHOUT ANY ERROR MESSAGE FROM IT !!

**Comment by tsdgeos** [comment]
i can confirm that this works fine on latest flatpak from flathub + archlinux for me

**Comment by eszlari** [comment]
Works here (Kubuntu 20.04) too.

**Comment by Nokia808** [comment]
I installed Libre Office from FlatHub & it's print preview work fine without such problem.

**Comment by Siosm** [comment]
I can not reproduce this issue on Fedora Workstation 32 with latest flatpak. Will try on Silverblue.

**Comment by Siosm** [comment]
I can not reproduce this on Kinoite (KDE Silverblue).

**Comment by Nokia808** [comment]
@Siosm 
What it could be the cause of this on my system ??!!! Does this could be due to type of printer drivers or DE?? I'm using Hp printer with hp rdiver (hplip) installed from official Fedor repositories. How can perform further investigation ?

**Comment by eszlari** [comment]
DE? Mate? Try another one?

**Comment by tsdgeos** [comment]
No, this is flatpak bug with setting all dates to day 0 which breaks caches, you can just manually remove the file at /home/YOUR_USER/.var/app/org.kde.okular/cache/ksycoca5* and it will work.

**Comment by Nokia808** [comment]
@tsdgeos 
So, you can finally discover the nature of this bug! I hope you will fix it in near feature.

**Comment by Nokia808** [comment]
Still not fixed with 20.12.3

**Comment by Nokia808** [comment]
Issue resolved since flatpak package version before current one. I was of no time to report this. Sorry for delay.
