### ISSUE TITLE
Annotation text does not appear in Ubuntu 20.04 after installing tex-gyre

### ISSUE THREAD

**Issue by Johannes222** [flathub/org.kde.okular#85]
The text of the annotations disappeared in Ubuntu 20.04 after installing the tex-gyre (20180621-3) package. Uninstalling tex-gyre fixed the issue.

**Comment by tsdgeos** [comment]
It doesn't seem like this would be a flatpak related issue, i'd say report it to bugs.kde.org and let upstream deal with it

**Comment by Johannes222** [comment]
I did report it here: https://bugs.kde.org/show_bug.cgi?id=423914
Thanks.
