### ISSUE TITLE
New annotation design not included in flatpak version !

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.kde.okular#87]
Hi. I'm not sure if this is bug or intended ! All what I see is that the new annotation design was already merged to master https://invent.kde.org/graphics/okular/-/merge_requests/105 but the old one still appearing to me on flatpak version.

I'm, now, on version 1.10.3

**Comment by Siosm** [comment]
This change has been merged into master but has not yet reached a stable release and is thus not included in this Flatpak. If you want to try it you can build from source or try the [KDE development Flatpaks](https://community.kde.org/Guidelines_and_HOWTOs/Flatpak).
