### ISSUE TITLE
In recent version 1.11 the actions are mostly wrong

### ISSUE THREAD

**Issue by Gabriel-p** [flathub/org.kde.okular#91]
(I'm translating from Spanish, so some of the names may differ sligthly)

1. The "Quick annotations" no longer stays fixed to the side of the document when clicked. Now it's a pop-up menu that hides after selecting a tool. Is this by design? Because it's very inconvenient.
2. "Underline" is a text note
3. "Strike through" is "Underline"
4. "Typewriter" is an emergent note
5. "Emergent note" is the action to draw free-hand
6. Arrows do nothing
....

**Comment by tsdgeos** [comment]
Report application bugs in bugs.kde.org
